import Head from 'next/head'
import Layout from '@/components/Layout'
import Image from 'next/image'
import bgImage from '../../public/images/bg-image.jpg'
import usman from '../../public/images/usman.jpg'
import khalid from '../../public/images/khalid.jpg'
import umar from '../../public/images/umar.jpg'
import salisu from '../../public/images/salisu.jpg'
import Link from 'next/link'
import { SiWebmoney } from 'react-icons/si'
import { FaDesktop } from 'react-icons/fa'
import { PiDevicesBold } from 'react-icons/pi'
import {
  TwitterIcon,
  GithubIcon,
  LinkedInIcon,
  LinkArrow,
} from '../components/Icons'

const Products = ({ title, summary, link }) => {
  return (
    <div
      id="products"
      className="col-span-1 md:col-span-3 flex flex-col gap-3 border-2 border-solid border-light p-6 "
    >
      <h3 className="text-xl md:text-lg font-semibold text-center text-secondary">
        {title}
      </h3>
      <p>{summary}</p>
      {link}
    </div>
  )
}

const Services = ({ service, icon }) => {
  return (
    <div id="services" className="col-span-1 md:col-span-3">
      <div className="flex flex-col md:flex-row justify-center items-center gap-16">
        <div className="md:w-full w-80 p-8 md:p-16 flex flex-col gap-y-6 text-center rounded-lg shadow-3xl hover:scale-110 hover:transition-all border-2 border-light border-solid">
          <p className="self-center">{icon}</p>
          <p className="">{service}</p>
        </div>
      </div>
    </div>
  )
}
const Team = ({
  fullName,
  name,
  bio,
  img,
  twitterLink,
  linkedInLink,
  githubLink,
}) => {
  return (
    <div className="col-span-1 md:col-span-4 flex flex-col gap-y-4 items-center p-4 py-6 border-2 border-solid border-light">
      <Image src={img} alt={name} className="w-44 h-44 rounded-full" />
      <h3 className="text-xl md:text-lg font-semibold">{fullName}</h3>
      <p className="text-base text-center">{bio}</p>
      <nav className="flex items-center justify-center flex-wrap">
        <a href={twitterLink} target={'_blank'} className="w-6 mr-3 sm:mx-1">
          <TwitterIcon />
        </a>
        <a
          href={githubLink}
          target={'_blank'}
          className="w-6 mx-3 bg-dark rounded-full sm:mx-1"
        >
          <GithubIcon />
        </a>
        <a href={linkedInLink} target={'_blank'} className="w-6 ml-3 sm:mx-1">
          <LinkedInIcon />
        </a>
      </nav>
    </div>
  )
}
export default function Home() {
  return (
    <>
      <Head>
        <title>AlyaumTech</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex items-center w-full min-h-screen my-6 bg-dark text-light">
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className="flex items-center justify-between gap-8 w-full lg:flex-col my-8">
            <div className="w-1/2 md:w-full">
              <Image
                src={bgImage}
                alt="backgound image"
                className="w-full h-auto lg:hidden md:inline-block md:w-full"
                priority
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center text-light">
              <h1 className="font-bold text-6xl text-left xl:text-6xl lg:text-center lg:text-6xl md:text-5xl sm:text-3xl">
                Turning Imaginations To Reality
              </h1>
              <p className="my-2 text-base font-medium md:text-sm sm:text-xs">
                We specialize in software solutions for growing businesses.
                Learn how customized software streamlines processes and helps
                you realize your dream of a thriving business.
              </p>
              <div
                id="contact"
                className="flex items-center self-start mt-2 lg:self-center"
              >
                <Link
                  href="mailto:usmanyahaya6967@gmail.com"
                  target="_blank"
                  className="flex items-center bg-dark text-light dark:bg-light dark:text-dark p-2 px-6 md:p-1.5 md:px-4 md:text-base rounded text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light"
                >
                  Contact <LinkArrow className={'w-6 ml-1'} />
                </Link>
              </div>
            </div>
          </div>
          <div className="my-32 grid grid-cols-2 gap-6">
            <div className="col-span-1 md:col-span-2 flex flex-col gap-y-2">
              <h2 className="font-bold text-xl md:text-lg text-secondary underline underline-offset-2">
                Mission
              </h2>
              <p className="text-lg">
                To empower businesses with cutting-edge software solutions,
                leveraging innovative technologies, and delivering exceptional
                value through tailored development services.
              </p>
            </div>
            <div
              className="col-span-1 md:col-span-2 flex flex-col gap-y-2"
              id="about"
            >
              <h2 className="font-bold text-xl md:text-lg text-secondary underline underline-offset-2 md:text-right">
                Vision
              </h2>
              <p className="text-lg">
                To be a leading software development partner for startups,
                recognized for our commitment to excellence, agility in
                delivery, and driving digital transformation through impactful
                solutions.
              </p>
            </div>
          </div>
          <div className="my-32 flex flex-col gap-3" id="products">
            <h2 className="text-center mb-12 text-4xl md:text-xl font-bold underline underline-offset-2">
              Our Products
            </h2>
            <div className="grid grid-cols-3 gap-6 items-center">
              <Products
                title="AlyaumHealth"
                summary="State and federal health and social services face increasing and often 
                evolving challenges. We help them find their way forward with products and services 
                designed to increase efficiency and improve health."
                link={
                  <Link
                    href="/alyaum.ng"
                    target="_blank"
                    className="mt-6 p-1 px-4 border border-solid border-light bg-secondary w-fit text-center text-light self-center"
                  >
                    Read more
                  </Link>
                }
              />
              <Products
                title="AlyaumAgro"
                summary="At AlyaumAgro, we focus on using the latest technology to optimize your agricultural processes. We drive innovation by making this technology accessible to farmers. "
                link={
                  <Link
                    href="/alyaum.ng"
                    target="_blank"
                    className=" mt-6 p-1 px-4 border border-solid border-light bg-secondary w-fit text-center text-light self-center"
                  >
                    Read more
                  </Link>
                }
              />
              <Products
                title="AlyaumLearn"
                summary="AlyaumLearn is committed to providing access to global experiences for all 
                through study abroad opportunities, scholarships, training and conferences, fellowships, 
                grants and awards, jobs, internships, and volunteer programs."
                link={
                  <Link
                    href="/alyaum.ng"
                    target="_blank"
                    className=" mt-6 p-1 px-4 border border-solid border-light bg-secondary w-fit text-center text-light self-center"
                  >
                    Read more
                  </Link>
                }
              />
            </div>
          </div>
          <div className="my-32" id="services">
            <h2 className="text-center mb-12 text-4xl md:text-xl font-bold underline underline-offset-2">
              Our Services
            </h2>
            <div className="grid grid-cols-3 gap-6 items-center">
              <Services
                service=" Web Development"
                icon={<SiWebmoney className="w-20 h-20 fill-secondary" />}
              />
              <Services
                service="Software Development"
                icon={<PiDevicesBold className="w-20 h-20 fill-secondary" />}
              />
              <Services
                service="Software Consultancy/Maintenance"
                icon={<FaDesktop className="w-20 h-20 fill-secondary" />}
              />
            </div>
          </div>
          <div className="my-32">
            <h2 className="text-center mb-12 text-4xl md:text-xl font-bold underline underline-offset-2">
              Our Team
            </h2>
            <div className="grid grid-cols-4 gap-2">
              <Team
                fullName="Usman Yahaya"
                name="usman"
                bio="Frontend Developer || Data Scientist || UI/UX Designer"
                img={usman}
                githubLink="https://github.com/Usmaniyya"
                twitterLink="hhtps://twitter.com/Y_Uthmaan"
                linkedInLink="hhtps://linkedin.com"
              />
              <Team
                fullName="Khalid Abdullahi"
                name="khalid"
                bio="Backend Developer || Data Analyst || Project Manager"
                img={khalid}
                githubLink="https://github.com/Usmaniyya"
                twitterLink="hhtps://twitter.com/Y_Uthmaan"
                linkedInLink="hhtps://linkedin.com"
              />
              <Team
                fullName="Umar Suleiman"
                name="umar"
                bio="Product Designer || UI/UX Designer || Software Analyst"
                img={umar}
                githubLink="https://github.com/Usmaniyya"
                twitterLink="hhtps://twitter.com/Y_Uthmaan"
                linkedInLink="hhtps://linkedin.com"
              />

              <Team
                fullName="Salisu Ibrahim"
                name="salisu"
                bio="Data Scientist || Data Analyst || Machine Learning Engineer"
                img={salisu}
                githubLink="https://github.com/Usmaniyya"
                twitterLink="hhtps://twitter.com/Y_Uthmaan"
                linkedInLink="hhtps://linkedin.com"
              />
            </div>
          </div>
        </Layout>
      </main>
    </>
  )
}
